version: '3'

services:
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: always
    networks:
      - proxy
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 10050:10050

networks:
  proxy:
    external: true

